<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>This is textmate syntax grammer for three</string>
	<key>fileTypes</key>
	<array>
		<string>3</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\b(namespace|module|struct|union|enum|def\s+\w+|if|switch|loop)\b</string>
	<key>foldingStopMarker</key>
	<string>end</string>
	<key>name</key>
	<string>Three</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.three</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(^[ \t]+)?(\/\/).*$\n?</string>
			<key>name</key>
			<string>comment.line.double-slash.three</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(private|public|end|enum)\b</string>
			<key>name</key>
			<string>keyword.structural.three</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if|unless|loop|break|return|switch|case|default|else|next|do|continue|or|and|cas|for)\b</string>
			<key>name</key>
			<string>keyword.control.three</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(barrier|atomic|abort)\b</string>
			<key>name</key>
			<string>keyword.control.three</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.three</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(namespace|import|module|struct)\s+([\w\.]+)</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0(x|b)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)\b</string>
			<key>name</key>
			<string>constant.numeric.three</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false|null)\b</string>
			<key>name</key>
			<string>constant.three</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.three</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.three</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(def)(:func)?\s+(\w+)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.three</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.three</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(def)(:type)\s+(\w+)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\s*(@\w+)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(linkage|include)\b</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.untitled</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.untitled</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.three</string>
	<key>uuid</key>
	<string>977E764F-65E7-4BDE-9FB7-AEA29A229125</string>
</dict>
</plist>
